### ISSUE TITLE
No AI

### ISSUE THREAD

**Issue by grizeldi** [jakobzmrzlikar/Battleship#8]
Readme.md promises an advenced AI opponent. I don't see any AI in your code.

**Comment by jakobzmrzlikar** [comment]
sej ga lahko ti nrdis :P

**Comment by grizeldi** [comment]
No it's your work :D

**Comment by grizeldi** [comment]
Whyyyyyyy?

**Comment by MikosJon** [comment]
I think there is AI, not quite sure.
